from pathlib import Path
p=Path('F:/ACMCM/2022D/delivery/ICM2022D_Revised/paper.tex')
s=p.read_text(encoding='utf-8')
def replace(old,new):
    global s
    assert old in s,old[:90]
    s=s.replace(old,new,1)
def bi(en,zh): return '\\bi{'+en+'}{'+zh+'}\\par\n'
def sub(en,zh): return '\\subpart{'+en+'}{'+zh+'}\n'
def step(n,en,zh): return '\\paragraph{Step '+str(n)+': \\bi{'+en+'}{'+zh+'}}\\par\n'
# The auxiliary selection model uses compact run-in stages; the main models use numbered subsections.
replace('\\subpart{Indicator dictionary and coverage model}{指标字典与覆盖筛选模型}\\par',
sub('Indicator dictionary and coverage model','指标字典与覆盖筛选模型')+
bi(r'\textbf{Motivation and design.} Collecting every available KPI consumes audit effort, while selecting only highly correlated indicators can omit rare but critical recovery or governance evidence. We therefore formulate minimum-cost requirement coverage: business obligations determine what must be represented, and cost chooses among acceptable panels.',r'\textbf{提出动因与设计逻辑。} 全量采集所有KPI会占用审核资源，仅按相关性筛选又可能遗漏低频但关键的恢复与治理证据。因此采用最小成本需求覆盖模型：先由业务义务确定必须覆盖的内容，再在合格面板之间比较采集成本。')+
bi(r'\textbf{Model construction.} Inputs are indicator definitions, the binary requirement--indicator matrix, collection costs, and mandatory checks; the output is an auditable high-frequency panel.',r'\textbf{模型构建。} 输入为指标定义、二元需求覆盖矩阵、采集成本和强制检查项，输出为可审计的高频指标面板。'))
needle='\\bi{The mandatory set is P2'
pos=s.index(needle)
s=s[:pos]+step(1,'encode requirements','编码需求')+bi('Set $A_{gi}=1$ exactly when indicator $i$ supplies evidence for requirement $g$; record effort $c_i$ in a common unit. Lock the mandatory indicators before searching.','仅当指标$i$能够提供需求$g$的证据时令$A_{gi}=1$，并统一记录工时成本$c_i$；搜索前锁定强制指标。')+step(2,'enumerate and screen','枚举与筛选')+bi('Enumerate all binary vectors $z\\in\\{0,1\\}^{16}$; discard a vector if any mandatory item is absent or any requirement has zero coverage.','枚举全部$z\\in\\{0,1\\}^{16}$，剔除缺少强制项或存在未覆盖需求的向量。')+step(3,'select and perturb costs','选优并扰动成本')+bi('Minimize total cost among surviving vectors, output their selected indicator IDs, then repeat after raising each individual cost by 20\\%. Compare the selected sets to assess local stability.','在可行向量中选择总成本最小者，输出指标编号；再依次将单项成本提高20\\%并重新求解，通过入选集合变化检查局部稳定性。')+bi(r'\textbf{Results and interpretation.} The stars in Table~\ref{tab:dict} display the selected panel and preserve its operational meaning.',r'\textbf{结果分析与展示。} 表\ref{tab:dict}以星号展示入选面板，并逐项保留其业务含义。')+s[pos:]
marker='\\subpart{Collection protocol and confidentiality}'
pos=s.index(marker)
s=s[:pos]+bi(r'\textbf{Performance and boundary.} Stable selection under one-at-a-time cost changes supports local robustness, not robustness to every joint change. Coverage depends on the declared matrix: a formally covered requirement can still be poorly measured. Independent review of definitions and audit quality is therefore needed before deploying the panel.',r'\textbf{性能讨论与适用边界。} 单项成本扰动下集合稳定，说明局部稳健性，但不保证任意联合扰动下仍然稳定。覆盖结果依赖所声明矩阵，形式上覆盖并不必然意味着测量质量充分，因此部署前仍应独立复核指标定义与审核质量。')+'\n'+s[pos:]
replace('\\subpart{From actions to latent capability}{从行动到潜在能力}',sub('Motivation and design logic','提出动因与设计逻辑')+bi('Monthly pass rates fluctuate with audit size and workload, while training and system changes take time to affect operations. A static score confounds these sources of variation. Inspired by state-space filtering, LCF separates an evolving latent capability from noisy measurements and places action delay in the transition equation. The objective is to recover a useful capability trajectory and forecast it without treating short-run KPI changes as immediate intervention effects.','月度通过率受审核样本量和负荷影响，培训及系统改造又需要时间才能产生效果。静态评分混合了这些变化来源。受状态空间滤波方法启发，LCF将持续演化的潜在能力与带噪观测分开，并在状态转移中显式引入行动延迟，以恢复可用于预测的能力轨迹，避免把短期KPI变化直接解释为干预效果。')+sub('Model construction: state and observation','模型构建：状态与观测')+bi('Inputs are monthly pass counts, audit denominators, workload, and dated actions. Outputs are three capability estimates, one-step forecasts, and conditional intervals; these estimates become CRM inputs.','输入为月度通过计数、审核分母、负荷与行动日期；输出为三维能力估计、一步预测和条件区间，再传入CRM。'))
replace('\\subpart{Stepwise filtering calculation}{滤波计算步骤}','\\subpart{Algorithm and stepwise computation}{算法设计与分步计算}')
replace('\\subpart{Comparing capability models on the same test period}{同一测试期的能力模型对比}','\\subpart{Results: comparison on the same test period}{结果分析：同一测试期的模型对比}')
needle='\\bi{Filtering reduces sampling noise'
pos=s.index(needle)
s=s[:pos]+bi('The lower pooled errors support using the filtered profile for subsequent scoring: the state estimate suppresses audit noise, and the delayed forecast better reflects the timing of actions. Figure~\\ref{fig:state} also preserves dimension-specific trajectories, so improvement in the aggregate does not hide a weak process capability.','总体误差下降支持将滤波画像用于后续评分：状态估计减少审核噪声，延迟预测更好地反映行动的时间效应。图\\ref{fig:state}同时保留分维度轨迹，避免总体改善掩盖流程能力偏弱。')+sub('Performance discussion and limitations','性能讨论与局限性分析')+s[pos:]
replace('\\subpart{Chain probability and interaction effects}{业务链概率与交互效应}',sub('Motivation and design logic','提出动因与设计逻辑'))
needle='\\begin{equation}\n\\operatorname{logit}p_k'
replace(needle,bi('A weighted sum of capabilities lacks a directly testable service interpretation; multiplying stage probabilities assumes independence that shared outages can violate. CRM instead models the observed whole-chain success event. A monotone logistic response encodes the expected direction of capability effects, while interaction and environmental controls separate complementarity from operating exposure.','能力加权和缺少可直接检验的服务含义，环节概率相乘则依赖可能被共享故障破坏的独立性。CRM因此直接建模整条业务链的成功事件，以单调逻辑响应约束能力作用方向，再用交互项和环境控制项区分能力互补与运营暴露。')+sub('Model construction and score definitions','模型构建与评分定义')+bi('Input is the capability vector with workload and outage status; output is import/export success probability and its weighted reference or operational score.','输入为能力向量、负荷与故障状态；输出为进出口成功概率及其加权参考分或运营分。')+needle)
replace('\\subpart{Separate comparable capability from current exposure}{区分可比能力与当前业务暴露}',r'\paragraph{\bi{Reference and operational scores.}{参考分与运营分。}}\par')
a=s.index('\\algo{2}');b=s.index('\n\\subpart{Reliability',a)
s=s[:a]+sub('Algorithm and stepwise computation','算法设计与分步计算')+step(1,'construct predictors and split samples','构造特征并划分样本')+bi(r'For profile $i$, form $X_i=(1,a_{Pi},a_{Ti},a_{Ri},a_{Pi}a_{Ri},c_i,o_i)$. Use 1,200 profiles for training, 300 for validation, and 300 for untouched testing. Each chain has its own binary response $y_{ik}$.',r'对画像$i$构造$X_i=(1,a_{Pi},a_{Ti},a_{Ri},a_{Pi}a_{Ri},c_i,o_i)$；1,200个画像用于训练，300个用于验证，另300个保留测试。每条业务链分别使用二元结果$y_{ik}$。')+step(2,'fit the constrained response','拟合约束响应')+bi(r'For each chain and candidate $\lambda\in\{0,0.001,0.01\}$, minimize penalized training log loss by L-BFGS-B. The intercept is unpenalized; $\theta_k$ contains the seven coefficients in the order of $X_i$:',r'对每条业务链和候选$\lambda\in\{0,0.001,0.01\}$，用L-BFGS-B最小化带惩罚的训练对数损失；截距不受惩罚，$\theta_k$按$X_i$顺序包含七个系数：')+r'''
\begin{equation}
\widehat\theta_{k,\lambda}=\arg\min_{\theta_k\in\mathcal B}\left\{\frac1{1200}\sum_{i\in\mathcal D_{\rm train}}\big[\log(1+e^{X_i\theta_k})-y_{ik}X_i\theta_k\big]+\frac\lambda2\sum_{j=1}^{6}\theta_{kj}^2\right\}.
\end{equation}
'''+bi(r'The numerical domain is $\mathcal B=[-8,3]\times[0,6]^4\times[-4,0]\times[-6,0]$. These bounds implement the sign restrictions and stabilize estimation in this demonstration.',r'数值约束域为$\mathcal B=[-8,3]\times[0,6]^4\times[-4,0]\times[-6,0]$，用于实现符号限制并稳定演示中的估计。')+step(3,'select, freeze, and evaluate','选择参数、冻结模型并评价')+bi('Choose the penalty with minimum validation Brier score for each chain. Freeze its coefficients, predict the test outcomes, and compare with the training-frequency baseline using the metrics below. Apply the same frozen mapping to the LCF profile to calculate reference and operational scores.','按每条业务链的验证Brier分数选择惩罚，随后冻结系数，对测试结果预测，并按下述指标与训练频率基线比较。使用同一冻结映射处理LCF画像，计算参考分与运营分。')+step(4,'propagate uncertainty','传递不确定性')+bi('Generate 1,000 joint state/coefficient draws, transform each into a maturity score, and report the 5th and 95th percentiles. Forward two whole draws near those percentiles to RIP, preserving each sampled parameter configuration.','生成1,000组状态与系数联合抽样，逐组转换为成熟度，输出5\\%和95\\%分位数；将接近两个分位数的完整参数组合传入RIP。')+s[b:]
replace('\\subpart{Reliability model comparison and uncertainty transfer}{可靠性模型对比与不确定性传递}','\\subpart{Results: reliability comparison and visualization}{结果分析：可靠性对比与可视化}')
pos=s.index('\\bi{The final filtered profile')
s=s[:pos]+sub('Performance discussion and uncertainty boundaries','性能讨论与不确定性边界')+s[pos:]
replace('\\subpart{Response with delay and diminishing returns}{含延迟与边际收益递减的响应}',sub('Motivation and design logic','提出动因与设计逻辑')+bi('A maturity deficit does not determine which project should be funded first. Equal spending overlooks unequal response curves; nominal optimization can exhaust a budget when costs rise. RIP connects the CRM service probabilities to incremental avoided loss and chooses a feasible menu against a declared scenario set. Diminishing returns discourage overconcentration, delays reward timely delivery, and dependencies prevent investment in integration without governance support.','成熟度缺口本身不能决定项目优先级。等额投入忽略响应曲线差异，名义优化则可能在成本上涨后突破预算。RIP将CRM服务概率转换为增量避免损失，在明确的情景集合中选择可行组合；边际收益递减抑制过度集中，延迟机制体现及时实施的价值，项目依赖防止缺少治理基础时直接推进集成。')+sub('Model construction: response, objective, and constraints','模型构建：响应、目标与约束')+bi('Inputs are capability states, fitted chain coefficients, project response assumptions, scenarios, budgets, and staff capacity. Outputs are project levels and start quarters with scenario-specific cost and net benefit.','输入为能力状态、业务链拟合系数、项目响应假设、情景、预算与人力；输出为项目投入级别及启动季度，同时给出各情景成本和净收益。')+r'\thirdpart{Delayed response}{延迟响应}')
replace('\\subpart{Monetary objective and feasibility}{货币目标与可行性}','\\thirdpart{Monetary objective and feasibility}{货币目标与可行性}')
replace('\\subpart{Parameters and the selected project menu}{参数设置与选定项目组合}','\\thirdpart{Scenario and parameter specification}{情景与参数设置}')
a=s.index('\\algo{3}');b=s.index('\\input{results/plan_table.tex}',a)
s=s[:a]+sub('Algorithm and stepwise computation','算法设计与分步计算')+step(1,'enumerate candidate menus','枚举候选组合')+bi('For each of five projects, enumerate seven options: off, or investment level 1, 2, or 3 starting in quarter 1 or 2. Their Cartesian product gives $7^5=16{,}807$ menus.','每个项目包含七个选项：不启动，或投入1、2、3单位并在第一或第二季度启动。五项目选项的笛卡尔积得到$7^5=16{,}807$种菜单。')+step(2,'screen feasible menus','筛选可行组合')+bi('Compute quarterly spending and staff use, then check every budget scenario, governance dependency, and the recovery floor. The 20\\% overrun envelope is the largest planning cost multiplier; 1,418 menus remain feasible.','计算各季度支出和人力，检查所有预算情景、治理依赖和恢复下限。规划成本最大上浮20\\%，筛选后保留1,418个可行菜单。')+step(3,'evaluate delayed scenario returns','计算延迟情景收益')+bi('For each feasible menu and scenario, evaluate effective investment, capability gain, chain success, avoided loss, and discounted net benefit in that order using the equations above. Record the minimum scenario return for each menu.','对每个可行菜单及情景，依次按上述公式计算有效投入、能力增量、业务链成功率、避免损失和折现净收益，记录该菜单的最小情景净收益。')+step(4,'select and independently stress-test','选优并独立压力测试')+bi('Select the menu with the greatest minimum return and output its levels, start dates, cost, and staffing. Exhaustive evaluation gives zero optimality gap within this finite menu. Freeze the selected menu before the 200 wider held-out shocks; record feasibility separately from return and regret.','选择最小情景收益最大的菜单，输出投入、启动时间、成本与人力。穷举使有限菜单内的最优性间隙为零。随后冻结组合，进行200个更宽范围的留出冲击测试，并分别记录可行性、收益和后悔值。')+sub('Results: project selection and model comparisons','结果分析：项目选择与模型对比')+s[b:]
replace('\\subpart{Comparing resource-allocation models}{资源配置模型对比}\n','')
pos=s.index('\\bi{Robust planning reduces violations')
s=s[:pos]+sub('Performance discussion and applicability','性能讨论与适用边界')+bi('The held-out comparison tests a wider cost envelope and an alternative response shape, rather than repeating only the scenarios used to optimize. Budget reoptimization in Figure~\\ref{fig:decisions} shows whether a spending change alters the actual selected menu. Together these checks assess decision stability and feasibility beyond the nominal score gain.','留出比较扩大成本范围并替换响应函数形式，避免仅重复优化时使用的情景。图\\ref{fig:decisions}中的预算重新优化进一步检验支出变化是否改变实际项目选择，两类检查共同评价名义评分增益之外的决策稳定性与可行性。')+s[pos:]
p.write_text(s,encoding='utf-8')
print('Updated model narratives in both languages.')
